// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    firebase_uid,
    username,
    display_name,
    avatar_url,
    bio,
    university,
    faculty,
    grade,
    country,
    plan
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, 'free'
)
RETURNING id, firebase_uid, username, display_name, avatar_url, bio, university, faculty, grade, country, plan, created_at, updated_at, default_question_count
`

type CreateUserParams struct {
	FirebaseUid string         `json:"firebase_uid"`
	Username    string         `json:"username"`
	DisplayName string         `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Bio         sql.NullString `json:"bio"`
	University  sql.NullString `json:"university"`
	Faculty     sql.NullString `json:"faculty"`
	Grade       sql.NullInt16  `json:"grade"`
	Country     sql.NullString `json:"country"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirebaseUid,
		arg.Username,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Bio,
		arg.University,
		arg.Faculty,
		arg.Grade,
		arg.Country,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.University,
		&i.Faculty,
		&i.Grade,
		&i.Country,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultQuestionCount,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, username, display_name, avatar_url, bio, university, faculty, grade, country, plan, created_at, updated_at, default_question_count FROM users
WHERE firebase_uid = $1
LIMIT 1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.University,
		&i.Faculty,
		&i.Grade,
		&i.Country,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultQuestionCount,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, firebase_uid, username, display_name, avatar_url, bio, university, faculty, grade, country, plan, created_at, updated_at, default_question_count FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.University,
		&i.Faculty,
		&i.Grade,
		&i.Country,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultQuestionCount,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, firebase_uid, username, display_name, avatar_url, bio, university, faculty, grade, country, plan, created_at, updated_at, default_question_count FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.University,
		&i.Faculty,
		&i.Grade,
		&i.Country,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultQuestionCount,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    username = $2,
    display_name = $3,
    avatar_url = $4,
    bio = $5,
    university = $6,
    faculty = $7,
    grade = $8,
    country = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, firebase_uid, username, display_name, avatar_url, bio, university, faculty, grade, country, plan, created_at, updated_at, default_question_count
`

type UpdateUserParams struct {
	ID          uuid.UUID      `json:"id"`
	Username    string         `json:"username"`
	DisplayName string         `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Bio         sql.NullString `json:"bio"`
	University  sql.NullString `json:"university"`
	Faculty     sql.NullString `json:"faculty"`
	Grade       sql.NullInt16  `json:"grade"`
	Country     sql.NullString `json:"country"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Bio,
		arg.University,
		arg.Faculty,
		arg.Grade,
		arg.Country,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.University,
		&i.Faculty,
		&i.Grade,
		&i.Country,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultQuestionCount,
	)
	return i, err
}

const updateUserQuestionSettings = `-- name: UpdateUserQuestionSettings :one
UPDATE users SET
    default_question_count = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, firebase_uid, username, display_name, avatar_url, bio, university, faculty, grade, country, plan, created_at, updated_at, default_question_count
`

type UpdateUserQuestionSettingsParams struct {
	ID                   uuid.UUID `json:"id"`
	DefaultQuestionCount int16     `json:"default_question_count"`
}

func (q *Queries) UpdateUserQuestionSettings(ctx context.Context, arg UpdateUserQuestionSettingsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserQuestionSettings, arg.ID, arg.DefaultQuestionCount)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.University,
		&i.Faculty,
		&i.Grade,
		&i.Country,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultQuestionCount,
	)
	return i, err
}
