// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: answers.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const upsertAnswer = `-- name: UpsertAnswer :one
INSERT INTO answers (
    user_id,
    question_id,
    user_answer,
    is_correct
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (user_id, question_id) DO UPDATE SET
    user_answer  = EXCLUDED.user_answer,
    is_correct   = EXCLUDED.is_correct,
    updated_at   = NOW()
RETURNING id, user_id, question_id, user_answer, is_correct, created_at, updated_at
`

type UpsertAnswerParams struct {
	UserID     uuid.UUID `json:"user_id"`
	QuestionID uuid.UUID `json:"question_id"`
	UserAnswer string    `json:"user_answer"`
	IsCorrect  bool      `json:"is_correct"`
}

func (q *Queries) UpsertAnswer(ctx context.Context, arg UpsertAnswerParams) (Answer, error) {
	row := q.db.QueryRowContext(ctx, upsertAnswer,
		arg.UserID,
		arg.QuestionID,
		arg.UserAnswer,
		arg.IsCorrect,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.UserAnswer,
		&i.IsCorrect,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
