// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getTimelinePostByID = `-- name: GetTimelinePostByID :one
SELECT
    p.id,
    p.user_id,
    p.question_id,
    p.book_id,
    p.field_id,
    p.body,
    COALESCE(p.book_title, b.title)::text AS book_title,
    p.question_count,
    p.type,
    p.repost_count,
    p.like_count,
    p.comment_count,
    p.created_at,
    p.updated_at,
    0::integer AS score,
    u.username,
    u.display_name,
    u.avatar_url,
    fi.name AS field_name
FROM posts p
JOIN users u ON p.user_id = u.id
LEFT JOIN books b ON p.book_id = b.id
LEFT JOIN fields fi ON p.field_id = fi.id
WHERE p.id = $1
LIMIT 1
`

type GetTimelinePostByIDRow struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	QuestionID    uuid.NullUUID  `json:"question_id"`
	BookID        uuid.NullUUID  `json:"book_id"`
	FieldID       uuid.NullUUID  `json:"field_id"`
	Body          sql.NullString `json:"body"`
	BookTitle     string         `json:"book_title"`
	QuestionCount int32          `json:"question_count"`
	Type          string         `json:"type"`
	RepostCount   int32          `json:"repost_count"`
	LikeCount     int32          `json:"like_count"`
	CommentCount  int32          `json:"comment_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	Score         int32          `json:"score"`
	Username      string         `json:"username"`
	DisplayName   string         `json:"display_name"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
	FieldName     sql.NullString `json:"field_name"`
}

func (q *Queries) GetTimelinePostByID(ctx context.Context, id uuid.UUID) (GetTimelinePostByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTimelinePostByID, id)
	var i GetTimelinePostByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.BookID,
		&i.FieldID,
		&i.Body,
		&i.BookTitle,
		&i.QuestionCount,
		&i.Type,
		&i.RepostCount,
		&i.LikeCount,
		&i.CommentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Score,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.FieldName,
	)
	return i, err
}

const listPostedQuestionsByPostID = `-- name: ListPostedQuestionsByPostID :many
SELECT
    q.id,
    q.question_type,
    q.body,
    q.options,
    q.correct_answer,
    q.explanation,
    pq.note,
    pq.sort_order
FROM post_questions pq
JOIN questions q ON q.id = pq.question_id
WHERE pq.post_id = $1
ORDER BY pq.sort_order ASC
`

type ListPostedQuestionsByPostIDRow struct {
	ID            uuid.UUID             `json:"id"`
	QuestionType  string                `json:"question_type"`
	Body          string                `json:"body"`
	Options       pqtype.NullRawMessage `json:"options"`
	CorrectAnswer string                `json:"correct_answer"`
	Explanation   sql.NullString        `json:"explanation"`
	Note          sql.NullString        `json:"note"`
	SortOrder     int32                 `json:"sort_order"`
}

func (q *Queries) ListPostedQuestionsByPostID(ctx context.Context, postID uuid.UUID) ([]ListPostedQuestionsByPostIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostedQuestionsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostedQuestionsByPostIDRow{}
	for rows.Next() {
		var i ListPostedQuestionsByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionType,
			&i.Body,
			&i.Options,
			&i.CorrectAnswer,
			&i.Explanation,
			&i.Note,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postExists = `-- name: PostExists :one
SELECT EXISTS(SELECT 1 FROM posts WHERE id = $1)
`

func (q *Queries) PostExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, postExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
