// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createQuestion = `-- name: CreateQuestion :exec
INSERT INTO questions (
    id,
    user_id,
    source_type,
    question_type,
    body,
    options,
    correct_answer,
    explanation,
    is_ai_generated,
    generation_id,
    highlight_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreateQuestionParams struct {
	ID            uuid.UUID             `json:"id"`
	UserID        uuid.UUID             `json:"user_id"`
	SourceType    string                `json:"source_type"`
	QuestionType  string                `json:"question_type"`
	Body          string                `json:"body"`
	Options       pqtype.NullRawMessage `json:"options"`
	CorrectAnswer string                `json:"correct_answer"`
	Explanation   sql.NullString        `json:"explanation"`
	IsAiGenerated bool                  `json:"is_ai_generated"`
	GenerationID  uuid.NullUUID         `json:"generation_id"`
	HighlightID   uuid.NullUUID         `json:"highlight_id"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) error {
	_, err := q.db.ExecContext(ctx, createQuestion,
		arg.ID,
		arg.UserID,
		arg.SourceType,
		arg.QuestionType,
		arg.Body,
		arg.Options,
		arg.CorrectAnswer,
		arg.Explanation,
		arg.IsAiGenerated,
		arg.GenerationID,
		arg.HighlightID,
	)
	return err
}

const findQuestionByID = `-- name: FindQuestionByID :one
SELECT
    id,
    user_id,
    source_type,
    question_type,
    body,
    options,
    correct_answer,
    explanation,
    is_ai_generated,
    generation_id,
    highlight_id,
    answer_count,
    correct_count
FROM questions
WHERE id = $1
LIMIT 1
`

type FindQuestionByIDRow struct {
	ID            uuid.UUID             `json:"id"`
	UserID        uuid.UUID             `json:"user_id"`
	SourceType    string                `json:"source_type"`
	QuestionType  string                `json:"question_type"`
	Body          string                `json:"body"`
	Options       pqtype.NullRawMessage `json:"options"`
	CorrectAnswer string                `json:"correct_answer"`
	Explanation   sql.NullString        `json:"explanation"`
	IsAiGenerated bool                  `json:"is_ai_generated"`
	GenerationID  uuid.NullUUID         `json:"generation_id"`
	HighlightID   uuid.NullUUID         `json:"highlight_id"`
	AnswerCount   int32                 `json:"answer_count"`
	CorrectCount  int32                 `json:"correct_count"`
}

func (q *Queries) FindQuestionByID(ctx context.Context, id uuid.UUID) (FindQuestionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findQuestionByID, id)
	var i FindQuestionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceType,
		&i.QuestionType,
		&i.Body,
		&i.Options,
		&i.CorrectAnswer,
		&i.Explanation,
		&i.IsAiGenerated,
		&i.GenerationID,
		&i.HighlightID,
		&i.AnswerCount,
		&i.CorrectCount,
	)
	return i, err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, question_type, body, options, correct_answer, explanation
FROM questions
WHERE id = $1
LIMIT 1
`

type GetQuestionByIDRow struct {
	ID            uuid.UUID             `json:"id"`
	QuestionType  string                `json:"question_type"`
	Body          string                `json:"body"`
	Options       pqtype.NullRawMessage `json:"options"`
	CorrectAnswer string                `json:"correct_answer"`
	Explanation   sql.NullString        `json:"explanation"`
}

func (q *Queries) GetQuestionByID(ctx context.Context, id uuid.UUID) (GetQuestionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getQuestionByID, id)
	var i GetQuestionByIDRow
	err := row.Scan(
		&i.ID,
		&i.QuestionType,
		&i.Body,
		&i.Options,
		&i.CorrectAnswer,
		&i.Explanation,
	)
	return i, err
}

const listQuestionsByCreatorID = `-- name: ListQuestionsByCreatorID :many
SELECT id, question_type, body, options, correct_answer, explanation
FROM questions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListQuestionsByCreatorIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

type ListQuestionsByCreatorIDRow struct {
	ID            uuid.UUID             `json:"id"`
	QuestionType  string                `json:"question_type"`
	Body          string                `json:"body"`
	Options       pqtype.NullRawMessage `json:"options"`
	CorrectAnswer string                `json:"correct_answer"`
	Explanation   sql.NullString        `json:"explanation"`
}

func (q *Queries) ListQuestionsByCreatorID(ctx context.Context, arg ListQuestionsByCreatorIDParams) ([]ListQuestionsByCreatorIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionsByCreatorID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionsByCreatorIDRow{}
	for rows.Next() {
		var i ListQuestionsByCreatorIDRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionType,
			&i.Body,
			&i.Options,
			&i.CorrectAnswer,
			&i.Explanation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveQuestionForUser = `-- name: SaveQuestionForUser :exec
INSERT INTO saved_questions (user_id, question_id, note, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, question_id)
DO UPDATE SET note = EXCLUDED.note, updated_at = NOW()
`

type SaveQuestionForUserParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	QuestionID uuid.UUID      `json:"question_id"`
	Note       sql.NullString `json:"note"`
}

func (q *Queries) SaveQuestionForUser(ctx context.Context, arg SaveQuestionForUserParams) error {
	_, err := q.db.ExecContext(ctx, saveQuestionForUser, arg.UserID, arg.QuestionID, arg.Note)
	return err
}

const updateQuestionStats = `-- name: UpdateQuestionStats :exec
UPDATE questions
SET
    answer_count  = answer_count + 1,
    correct_count = correct_count + CASE WHEN $2::boolean THEN 1 ELSE 0 END,
    updated_at    = NOW()
WHERE id = $1
`

type UpdateQuestionStatsParams struct {
	ID        uuid.UUID `json:"id"`
	IsCorrect bool      `json:"is_correct"`
}

func (q *Queries) UpdateQuestionStats(ctx context.Context, arg UpdateQuestionStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateQuestionStats, arg.ID, arg.IsCorrect)
	return err
}
