// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate_limits.sql

package sqlcgen

import (
	"context"
)

const incrementRateLimitCounter = `-- name: IncrementRateLimitCounter :one
INSERT INTO rate_limit_counters (user_id, bucket, period, count)
VALUES ($1, $2, CURRENT_DATE, 1)
ON CONFLICT (user_id, bucket, period)
DO UPDATE SET count = rate_limit_counters.count + 1,
              updated_at = NOW()
RETURNING count
`

type IncrementRateLimitCounterParams struct {
	UserID string `json:"user_id"`
	Bucket string `json:"bucket"`
}

func (q *Queries) IncrementRateLimitCounter(ctx context.Context, arg IncrementRateLimitCounterParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementRateLimitCounter, arg.UserID, arg.Bucket)
	var count int64
	err := row.Scan(&count)
	return count, err
}
