// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const followUser = `-- name: FollowUser :execrows
INSERT INTO follows (follower_id, followee_id)
VALUES ($1, $2)
ON CONFLICT (follower_id, followee_id) DO NOTHING
`

type FollowUserParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, followUser, arg.FollowerID, arg.FolloweeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listCommentsByPostID = `-- name: ListCommentsByPostID :many
SELECT
    c.id,
    c.post_id,
    c.user_id,
    u.username,
    u.display_name,
    u.avatar_url,
    c.content,
    c.created_at
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.post_id = $1
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type ListCommentsByPostIDParams struct {
	PostID uuid.UUID `json:"post_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListCommentsByPostIDRow struct {
	ID          uuid.UUID      `json:"id"`
	PostID      uuid.UUID      `json:"post_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Username    string         `json:"username"`
	DisplayName string         `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Content     string         `json:"content"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) ListCommentsByPostID(ctx context.Context, arg ListCommentsByPostIDParams) ([]ListCommentsByPostIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByPostID, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByPostIDRow{}
	for rows.Next() {
		var i ListCommentsByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowUser = `-- name: UnfollowUser :execrows
DELETE FROM follows
WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowUserParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unfollowUser, arg.FollowerID, arg.FolloweeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
