ALTER TABLE highlights
    ALTER COLUMN book_id DROP NOT NULL;

ALTER TABLE highlights
    ADD COLUMN IF NOT EXISTS book_title TEXT,
    ADD COLUMN IF NOT EXISTS book_author TEXT,
    ADD COLUMN IF NOT EXISTS asin TEXT,
    ADD COLUMN IF NOT EXISTS highlighted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS source VARCHAR(20) NOT NULL DEFAULT 'manual',
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
